### PR TITLE
Fix Auto Insert XML Comment Issue

### LINKED ISSUE #6039: ENTER key does not work on lines following XML comments
Type: <b>Bug</b>

## Issue Description ##
Pressing <kbd>enter</kbd> on a line that follows an XML comment comments out that line of code.
## Steps to Reproduce ##
1) Create a new C# class file.
2) Add an XML comment to the class
image

3) Navigate to the class declaration line (line 9)
4) Press <kbd>enter</kbd>

## Expected Behavior ##
A new line is created
## Actual Behavior ##
A new line is created below, and the current line is commented out.
image

## Environment information ##

**VSCode version**: 1.81.0
**C# Extension**: 2.0.320
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.9 [c:\Users\\[UserName]\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.9\shared\Microsoft.NETCore.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|code-spell-checker|streetsidesoftware|2.20.5|streetsidesoftware.code-spell-checker-2.20.5|
|csharp|ms-dotnettools|2.0.320|ms-dotnettools.csharp-2.0.320-win32-x64|
|csharpextensions|kreativ-software|1.7.3|kreativ-software.csharpextensions-1.7.3|
|githistory|donjayamanne|0.6.20|donjayamanne.githistory-0.6.20|
|msbuild-project-tools|tintoy|0.4.9|tintoy.msbuild-project-tools-0.4.9|
|todo-tree|Gruntfuggly|0.0.226|gruntfuggly.todo-tree-0.0.226|
|vs-keybindings|ms-vscode|0.2.1|ms-vscode.vs-keybindings-0.2.1|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|ms-dotnettools.vscode-dotnet-runtime-1.6.0|;

</details>

Extension version: 2.0.320
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.92GB free)|
|Process Argv|--crash-reporter-id 30e1e2f9-1f87-49f9-91f0-3d5b0d6c5e66|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

### PR DESCRIPTION
**Pull request by akhera99**
Fixes #6039

### CODE REVIEW

File: src/lsptoolshost/roslynLanguageServer.ts [hunk 1]
```diff
@@ -861,9 +861,11 @@ async function applyAutoInsertEdit(
     token: vscode.CancellationToken
 ) {
     const change = e.contentChanges[0];
-
-    // Need to add 1 since the server expects the position to be where the caret is after the last token has been inserted.
-    const position = new vscode.Position(change.range.start.line, change.range.start.character + 1);
+    // Need to add a modifier since the server expects the position to be where the caret is after the last token has been inserted.
```
Comment (dibarbet) [inline src/lsptoolshost/roslynLanguageServer.ts:864]:
```suggestion
    // The server expects the request position to represent the caret position in the text after the change has already been applied.
    // We need to calculate what that position would be after the change is applied and send that to the server.
```

**Review by dibarbet — APPROVED** [review]
